[build]
  command = "mkdir -p .output/public && cp index.html _redirects .output/public/"
  publish = ".output/public"

[[redirects]]
  from = "/*"
  to = "https://lambuage.com/app/:splat"
  status = 301
  force = true
